package spring.bricole.common;

public enum EventType {
    LOGIN,
    LOGOUT,
    SIGNUP,
    PASSWORD_RESET,
    PROFILE_UPDATE,
    JOB_APPLICATION,
    JOB_OFFER,
    JOB_REJECTION,
    JOB_ACCEPTANCE,
    JOB_COMPLETION,
    REVIEW_SUBMISSION,
    REVIEW_UPDATE,
    REVIEW_DELETION,
    ACCOUNT_SUSPENSION,
    ACCOUNT_ACTIVATION,
    ACCOUNT_DELETION,
    ACCOUNT_BAN,
    ACCOUNT_UNBAN
}
